WORKDIR /var/www/html

###########################################################################
# Prepare webserver
###########################################################################

COPY .docker/nginx/default.conf.stg /etc/nginx/conf.d/default.conf
COPY .docker/nginx/www.conf /etc/php/7.3/fpm/pool.d/www.conf
COPY .docker/nginx/startup.sh /docker-entrypoint.d
COPY .docker/nginx/schedule-cron /etc/cron.d/schedule-cron
RUN chmod 0644 /etc/cron.d/schedule-cron
RUN chmod +x /docker-entrypoint.d/startup.sh

###########################################################################
# Prepare distribution
###########################################################################

COPY ./ /var/www/html

##### Reset permission #####

## RUN find /var/www/html -type d -exec chmod 755 {} \;
## RUN find /var/www/html -type f -exec chmod 644 {} \;
## RUN chown -R root:root /var/www/html

RUN chmod 777 -R /var/www/html/storage
RUN chmod +x /var/www/html/artisan

