version: "3.4"

services:
  ipp_api:
    build: ./nginx
    container_name: ipp_api
    volumes:
      - ./nginx/default.conf.local:/etc/nginx/conf.d/default.conf
      - ./nginx/startup.sh:/docker-entrypoint.d/startup.sh
      - ./nginx/www.conf:/etc/php/7.3/fpm/pool.d/www.conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/schedule-cron:/etc/cron.d/schedule-cron
      - ../:/var/www/html
    ports:
      - 80:80
    networks:
      - dev_network
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - dev_volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - dev_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - mariadb
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=mariadb
    ports:
      - 8080:80
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge

volumes:
  dev_volume:
    driver: local
